### PR TITLE
fix priority of macher for record pics

### PR DESCRIPTION
**Pull request by lgc2333**

### CODE REVIEW

**Comment by lgc2333** [comment]
pr了 快给我透（bushi

**Comment by lgc2333** [comment]
<https://github.com/synodriver/nonebot_plugin_picsearcher/pull/17/commits/343f9b11917253bc5a7e7de83ee6afb0649820f7> #16

**Comment by synodriver** [comment]
nb2更新了些骚东西，需要用hasattr判断或者getattr的时候给默认值，不然会AttributeError

**Comment by synodriver** [comment]
晚点我来加点料

**Pull request merged**
